var deceased = [
  'department stores',
  'automobiles',
  'the insurance industry',
  'summer vacations',
  'sick days',
  'cellphones',
  'film cameras',
  'bar soap',
  'McDonalds',
  'Applebee\'s',
  'crowdfunding',
  'regular toast',
  '9-to-5 workdays',
  'working from home',
  'brunch',
  'the Olympics',
  'international diplomacy',
  'the dinosaurs',
  'the ancient Egyptians',
  'canned beverages',
  'farmer\'s markets',
  'loyalty programs',
  'air travel',
  'travel agents',
  'love at first sight',
  'casual sex',
  'capitalism (JK, not yet)',
  'annual physicals',
  'taxi cabs',
  'gym memberships',
  'saunas',
  'steamrooms',
  'movies',
  'puppet shows',
  'knee-high socks',
  'soccer uniforms',
  'the American Dream',
  'democracy',
  'mascara',
  'stilletos',
  'boots',
  'most endangered species',
  'research grants',
  'study abroad programs',
  'matchmakers',
  'first dates',
  '80s fashion',
  'perms',
  'watercolor painting',
  'bibs in restaurants',
  'magazines',
  'newspapers',
  'the Gameboy Color',
  'your firstborn child',
  'two-parent households',
  'palm trees in land-locked states',
  'front porches',
  'porchswings',
  'high school math class',
  'fingerpaints',
  'massages',
  'lizards as pets',
  'doghouses',
  'litter boxes',
  'stamps',
  'stationary',
  'dining etiquette',
  'wedding receptions',
  'bachelorette parties',
  'bachelor parties',
  'bridal gowns',
  'tuxedos',
  'heterosexuality',
  'tax benefits for couples',
  'studio apartments',
  'health insurance',
  'auto insurance',
  'serif fonts',
  'AOL instant messenger',
  'wall-mounted singing bass',
  'gon\' fishin\' signs',
  'dogs to beware of',
  'wrought iron fences',
  'poison ivy cures',
  'grilled cheese with tomato soup',
  'standing on one foot',
  'morning commutes',
  'photos of sunsets',
  'leaky pipes',
  'musty smells',
  'mothballs',
  'scented candles',
  'earbuds',
  'ice skating',
  'biking for pleasure',
  'barn owls',
  'plug and play drivers',
  'dial-up internet',
  'the many worlds theory',
  'primetime Emmys',
  'the video star',
  'sandals',
  'boardwalks',
  'county fairs',
  'running with the bulls',
  'debutante balls',
  'playing with legos',
  'make-believe friends',
  'light-brites',
  'twist-off bottlecaps',
  'junkmail',
  'package management software',
  'DNS resolution',
  'RNA',
  'mitosis',
  'most lizards',
  'pine trees',
  'air fresheners',
  'drive-thru car washes',
  'golfcarts',
  'country clubs',
  'playing cards',
  'tarot reading',
  'craigslist ads',
  'train travel',
  'mental healthcare',
  'venetian blinds',
  'pottery classes',
  'that scene in Ghost',
  'conspiracy theories',
  'EGOT-ing',
  'easy mac',
  'sloppy joes',
  'naming hurricanes',
  'waterfront property',
  'condo timeshares',
  'tupperware parties',
  'leftovers',
  'Hayao Miyazaki films',
  'high school marching bands',
  'sonnets',
  'haiku poems',
  'pathetic fallacy',
  'nearly everything phallic',
  'bowling shoes',
  'tee-ball bats',
  'loose leaf tea',
  'oven mitts',
  'tin whistle solos',
  'out of tune violins',
  'pet birds',
  'fields of blueberries',
  'tulips',
  'votive candles',
  'scented candles',
  'plungers',
  'knife blocks',
  'vacuum cleaners',
  'artisan sodas',
  'illegal drugs',
  'realtor fees',
  'tap water',
  'proms',
  'homecoming dances',
  'high school football',
  'collegiate sports',
  'powerwalking',
  'exercise videos',
  'jazzercise',
  'swimlanes',
  'public pools',
  'speedos',
  't-squares',
  'compasses',
  'modernist architecture',
  'cubism',
  'social security',
  'air conditioning',
  'eating dessert first',
  'pairing red wine with beef',
  'sherry glasses',
  'zen gardens',
  'wine cellars',
  'birch soda',
  'hand grenades',
  'pomegranate juice',
  'chalkboard paint',
  'full-length mirrors',
  'bathroom tile',
  'fresh-baked cookies',
  'matchboxes',
  'the dramedy genre',
  'documentary narration',
  'waterfalls',
  'swimming in creeks',
  'rhubarb pie',
  'alarm clocks',
  'functional typewriters',
  'those hats from the navy',
  'shopping malls',
  'meatballs served with spaghetti',
  'bassoon solos',
  'seashells',
  'mushroom farms',
  'oak barrel aging',
  'boxer-briefs',
  'fireflies',
  'home fireworks',
  'wrist wallets',
  'fanny packs',
  'photo id',
  'coupons',
  'Magic: the Gathering',
  'piñatas',
  'laboratory mice',
  'tall dark and handsome strangers',
  'Disney movies',
  'theme parks',
  'standing in line',
  'garbage cans',
  'doorbells',
  'inkjet printers',
  'grand pianos',
  'flatscreen tvs',
  'the Nazcan plains',
  'solar eclipses',
  'salt and pepper',
  'tasting food when cooking',
  'brioche buns',
  'reality television',
  'utility bills',
  'rose windows',
  'rose-colored glasses',
  'aviator sunglasses',
  'earplugs',
  'reindeer',
  'holidays with the family',
  'juggling',
  'fireplaces',
  'incense',
  'bodegas',
  'buy-one-get-one sales',
  'tin foil hats',
  'subwoofers',
  'party subs',
  'karaoke booths',
  'over the counter medicine',
  'furbies',
  'food that shouldn\'t include lobster but does',
  'surf and turf',
  'horse racing',
  'turn signals',
  'parking tickets',
  'freeway driving',
  'audiobooks',
  'reporting on politics',
  'javascript',
  'the caesar salad',
  'late night television',
  'baseball hats',
  'American football games',
  'chewing tobacco',
  'waterparks',
  'trained dolphins',
  'zoo habitats',
  'eyeglasses',
  'cosplaying',
  'retro videogames',
  'the great American novel',
  'op-ed pieces',
  'cruising in person',
  'personal websites',
  'talking on the phone',
  'text messaging',
  'emoticons',
  'jigsaw puzzles',
  'sitcom television',
  'Dollywood',
  'satirical journalism',
  'Amelia Earhart',
  'the wardrobe from The Lion, The Witch, and the Wardrobe',
  'paintings of tigers',
  'those paintings done on velvet canvases',
  'bubblewrap',
  'hungry-looking owls',
  'Our Lady of Guadalupe',
  'peanut butter and jelly sandwiches',
  'Trader Joes frozen meals',
  'that olive bar at Whole Foods',
  'Olive Garden gift certificates',
  'bowling shoes',
  'Judy Garland\'s legacy',
  'hand-chipped ice',
  'old-fashioned seltzer bottles',
  'handlebar moustaches',
  'man buns',
  'multi-tiered cakes',
  'paper delivery routes',
  'degrees in ethnomusicology',
  'hot springs',
  'hookup apps',
  'hookah bars',
  'nut milks',
  'kale salads with nothing else on them',
  'embroidered birds',
  'relational databases',
  'Breakfast at Tiffany\'s',
  'subsitute teachers who put on a movie',
  'power tools',
  'Kundalini yoga',
  'knuckle tattoos',
  'kelp forests',
  'baby hippos (but we love you Fiona)',
  'clean energy',
  'mountaintop removal',
  'fracking',
  'jazz hands',
  'pho places with numbers in their names',
  'shiba inu puppies',
  'pickling anything',
  'brining the Thanksgiving turkey',
  'the seventh day of Christmas',
  'migratory birds',
  'salmon swimming upstream',
  'bottled water',
  'freckles',
  'gingivitis',
  '"this one weird trick"',
  'bento boxes',
  'lunch boxes with a thermos',
  'cease-and-desist letters',
  'secretaries of state',
  'eggs benedict',
  'rosary beads',
  'angel statues',
  'Dance Dance Revolution',
  'communist revolutions',
  'monogamy',
  'making 30 Rock references',
  'sushi rolls',
  'tummy scritches for large dogs',
  'visits to the dogpark',
  'playing mulitplayer in Goldeneye 007',
  'ice fishing',
];

function reload() {
  var answer = deceased[Math.floor(Math.random() * deceased.length)];
  document.getElementById("placeholder").innerHTML = answer;
}

function about() {
  document.getElementById("about-overlay").classList.remove('about-overlay-is-hidden');
  document.getElementById("about-overlay").onclick = function () {
    document.getElementById("about-overlay").classList.add('about-overlay-is-hidden');
    document.getElementById("about-overlay").onclick = null;
  };
}

document.addEventListener("DOMContentLoaded", function() {
  reload();
  document.getElementById("reload").onclick = reload;
  document.getElementById("about").onclick = about;
});
